### ISSUE TITLE
Lend button on Borrow detail page is not functioning

### ISSUE THREAD

**Issue by yukiwaki** [Loanyee/app#27]
On borrow detail page, 

We have two buttons, approve and lend.
Approve button should call approve() function and lend should call lend() function

![Image](https://user-images.githubusercontent.com/90386676/202055976-e47fcddd-519e-4272-a59f-3172c964d1cf.png)

**Comment by yukiwaki** [comment]
Approve : {.env file}
Lend : Supply collateral

**Comment by ericy-eth** [comment]
Approve button fixed.
Lend button fixed.

Lender confirmed receive stream in superfluid dashboard.

Borrower confirmed received borrow amount
<img width="1164" alt="Screenshot 2022-11-24 at 7 34 58 PM" src="https://user-images.githubusercontent.com/102403069/203896316-901d4daf-83f7-466a-aad5-f193344b711d.png">

<img width="1206" alt="Screenshot 2022-11-24 at 7 33 50 PM" src="https://user-images.githubusercontent.com/102403069/203896211-ab1ac571-d39e-4062-b4fc-bc56578dfa98.png">
